"use client";
import { useState } from "react";
type Asset={id:string;title:string;prompt:string;model:string;created:string;colour:string};
const initial:Asset[]=[
{id:"b2_8fa21",title:"A quiet place",prompt:"Editorial architecture photograph, brutalist sanctuary at dusk, soft amber windows",model:"gpt-image-1",created:"Today · 10:42",colour:"linear-gradient(135deg,#203a37,#c88a54)"},
{id:"b2_8fa20",title:"Solar forms",prompt:"Abstract solar panels as a modernist paper collage, deep navy and saffron",model:"gpt-image-1",created:"Yesterday",colour:"linear-gradient(135deg,#152640,#df9d36)"},
{id:"b2_8fa18",title:"Night signal",prompt:"Atmospheric electronic music loop, warm analogue synths",model:"Stability Audio",created:"Jul 20",colour:"linear-gradient(135deg,#311c54,#d05d98)"}];
export default function Home(){
 const [assets,setAssets]=useState(initial),[active,setActive]=useState(initial[0]),[prompt,setPrompt]=useState("A quiet, sunlit reading room shaped by the coastal landscape, editorial architecture photography"),[creating,setCreating]=useState(false),[notice,setNotice]=useState("");
 async function create(){if(!prompt.trim())return;setCreating(true);try{const r=await fetch("/api/generate",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({prompt})});const d=await r.json();const item={id:d.id,title:"Untitled generation",prompt,model:d.model,created:"Just now",colour:"linear-gradient(135deg,#263e4b,#d58a64)"};setAssets(x=>[item,...x]);setActive(item);setNotice(d.mode==="live"?"Generated and archived to B2.":"Demo asset created — connect credentials for live generation.");}catch{setNotice("Demo asset created locally.");}finally{setCreating(false)}}
 return <main><aside><div className="mark"><span>◇</span> Provenance<br/>Studio</div><nav><a className="selected">Library</a><a>Workflows</a><a>Storage</a><a>Settings</a></nav><div className="quota"><small>B2 STORAGE</small><strong>2.4 GB <em>of 10 GB</em></strong><div><i/></div><p>24,390 stored objects</p></div><div className="profile"><b>NK</b><span>New creator<small>Free workspace</small></span></div></aside><section className="content"><header><div><p className="eyebrow">WORKSPACE / ALL MEDIA</p><h1>Your media, with its story intact.</h1></div><button className="outline">⌘ K &nbsp; Search</button></header><div className="hero"><div><p className="eyebrow">CREATE A PROVENANCED ASSET</p><h2>From idea to durable evidence.</h2><p>Generate media through a tracked workflow. Every output arrives with its inputs, settings, and lineage.</p></div><div className="composer"><textarea value={prompt} onChange={e=>setPrompt(e.target.value)}/><div><span>Image · gpt-image-1</span><button onClick={create} disabled={creating}>{creating?"Generating…":"Generate ↗"}</button></div></div></div>{notice&&<div className="notice">● {notice}</div>}<div className="library-head"><h2>Recent assets <span>{assets.length}</span></h2><button className="outline">All media ⌄</button></div><div className="grid">{assets.map(a=><button className={active.id===a.id?"card active":"card"} onClick={()=>setActive(a)} key={a.id}><div className="art" style={{background:a.colour}}><span>✦</span><small>{a.model.includes("Audio")?"AUDIO":"IMAGE"}</small></div><div className="cardcopy"><strong>{a.title}</strong><p>{a.created}</p></div></button>)}</div></section><aside className="detail"><div className="detailtop"><span>ASSET DETAIL</span><button>×</button></div><div className="largeart" style={{background:active.colour}}>✦</div><h2>{active.title}</h2><p className="muted">{active.created} · <code>{active.id}</code></p><hr/><p className="label">GENERATION RECORD</p><dl><dt>Workflow</dt><dd>image-generate-v1</dd><dt>Provider / model</dt><dd>{active.model}</dd><dt>Storage</dt><dd className="ok">● B2 archived</dd></dl><p className="label">PROMPT</p><blockquote>{active.prompt}</blockquote><button className="provenance">View full provenance <span>→</span></button><button className="download">↓ &nbsp; Download original</button></aside></main>;
}
